###**Reg No - GO_STP_11828**

####**Name - Srikant Kumar Maharana**

###**Assignment 4**

1 .Import the numpy package under the name np and Print the numpy version and the
conguration

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())


1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2.Create a null vector of size 10

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3.Create Simple 1-D array and check type and check data types in array

In [3]:
import numpy as np
a = np.array([5, 4, 3])   
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


4.How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
import numpy as np
a = np.array([20,26,55])
print("Size of the array: ",a.size)
print("Memory size of array element in bytes: ",a.itemsize) 
print("Memory size in bytes:",a.size * a.itemsize)

Size of the array:  3
Memory size of array element in bytes:  8
Memory size in bytes: 24


5.Create a null vector of size 10 but the fifth value which is 1

In [5]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6.Create a vector with values ranging from 10 to 49

In [6]:
import numpy as np
a = np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


7.Reverse a vector (first element becomes last)

In [8]:
import numpy as np
x = np.arange(1, 25)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Reverse array:
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


8.Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



9.Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
import numpy as np
nums = np.array([1,2,0,0,4,0])
print("Indices of elements equal to zero of the said array:")
result = np.where(nums != 0)[0]
print(result)

Indices of elements equal to zero of the said array:
[0 1 4]


10.Create a 3x3 identity matrix

In [13]:
import numpy as np
x=np.eye(3)
print('3x3 matrix:')
print(x)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.Create a 3x3x3 array with random values

In [14]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.77511038 0.70235903 0.45938777]
  [0.02241515 0.1144697  0.67172619]
  [0.43023922 0.83153068 0.70118278]]

 [[0.66654827 0.23342151 0.74362802]
  [0.39264847 0.89807376 0.97957383]
  [0.82428275 0.46279509 0.13610139]]

 [[0.38803395 0.40164277 0.35767692]
  [0.31357417 0.97760425 0.86005527]
  [0.44984978 0.54198396 0.35633519]]]


12.Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
import numpy as np
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Minimum and Maximum Values:
0.003087784268758109 0.9897878416258642


13.Create a random vector of size 30 and find the mean value

In [16]:
import numpy as np
x = np.random.random(30)
print(x)
print(np.mean(x))

[0.7652247  0.79697786 0.23549759 0.42144857 0.53260926 0.68738438
 0.41689295 0.3314483  0.01239619 0.21626812 0.99418346 0.46676908
 0.82978668 0.58674725 0.05207    0.02725333 0.5741308  0.05562277
 0.6337302  0.83313418 0.78037917 0.544527   0.85791824 0.01138682
 0.10688019 0.82719475 0.69432159 0.88111868 0.81881828 0.86259495]
0.5284905118553725


14.Create a 2d array with 1 on the border and 0 inside

In [18]:
import numpy as np
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


15.How to add a border (filled with 0's) around an existing array?

In [19]:
import numpy as np
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [20]:
import numpy as np
Arr= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(Arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
print(Arr[1,5])


13


In [22]:
print(Arr[0,:])

[1 2 3 4 5 6 7]


In [23]:
print(Arr[:,2])

[ 3 10]


In [24]:
print(Arr[0,:][1:6:2])

[2 4 6]


In [25]:
Arr[1,5]=20
print(Arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


17.How to Convert a 1D array to a 2D array with 2 rows

In [28]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])
newarray = array.reshape(2, 3)
print(newarray)

[[1 2 3]
 [4 5 6]]


18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:
a = np.array([1,2,3])

Desired Output:
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [29]:
import numpy as np
a=np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


19.Write a program to show how Numpy taking less memory compared to Python List?

In [30]:
import numpy as np
import sys
S= range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S)) 
D= np.arange(1000)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


20.Write a program to show how Numpy taking less time compared to Python List?

In [31]:
import numpy
import time
size = 1000000  
list1 = range(size)
list2 = range(size)
array1 = numpy.arange(size)  
array2 = numpy.arange(size)
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]
print("Time taken by Lists to perform multiplication:",(time.time() - initialTime),"seconds")
initialTime = time.time()
resultantArray = array1 * array2
print("Time taken by NumPy Arrays to perform multiplication:",(time.time() - initialTime),"seconds")

Time taken by Lists to perform multiplication: 0.12540555000305176 seconds
Time taken by NumPy Arrays to perform multiplication: 0.003839254379272461 seconds
